default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 5598
  host: localhost

development:
  <<: *default
  database: Mybd_d

test:
  <<: *default
  database: Mybd_t

production:
  <<: *default
  database: Mybd
  username: postgres
  password: <%= ENV['5598'] %>
  url: <%= ENV['DATABASE_URL'] %>